IDENTIFICATION DIVISION.
  PROGRAM-ID. CobAll.

ENVIRONMENT DIVISION.
  INPUT-OUTPUT SECTION.
    FILE-CONTROL.
      SELECT Debug-Log-File ASSIGN TO 'Debug.log'
      ORGANISATION LINE SEQUENTIAL
      ACCESS MODE SEQUENTIAL.

PROCEDURE DIVISION.
  DISPLAY 'Hello World'.
  STOP RUN.

END PROGRAM CobAll.
