name: Lint and Compile

# TODO => Add pull_request trigger at v1.0.0
on: [workflow_dispatch, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up GnuCOBOL
        uses: fabasoad/setup-cobol-action@v1.6.1
      - name: Lint code
        run: cobc -fsyntax-only -I ./src -I ./src/ui ./src/*.cob -Wall -Wextra -Wno-terminator

  compile:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up GnuCOBOL
        uses: fabasoad/setup-cobol-action@v1.6.1
      - name: Compile code
        run: cobc -I ./src -I ./src/ui -x ./src/main.cob ./src/*.cob -o CobAll -w -q
