name: Lint and Compile

# TODO => Add pull_request trigger at v1.0.0
on: [workflow_dispatch, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up GnuCOBOL
        uses: fabasoad/setup-cobol-action@v1.6.1
      - name: Lint code
        run: |
          cobc -free
          -fsyntax-only
          -I ./src
          -I ./src/ui
          -I ../src/ui/error-scr ^
          ./src/*.cob
          -Wall -Wextra
          -Wno-terminator

  compile:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up GnuCOBOL
        uses: fabasoad/setup-cobol-action@v1.6.1
      - name: Compile code
        run: |
          cobc -free
          -I ./src
          -I ./src/ui
          -I ../src/ui/error-scr
          -x ./src/main.cob
          ./src/*.cob
          -o CobAll
          -w -q
